### ISSUE TITLE
Check permissions

### ISSUE THREAD

**Issue by adimajo** [patrickshox/Mojave-Dark-RStudio-Theme#1]
I got permission errors:
Error in value[[3L]](cond) : 
  Unable to add the theme file "https://raw.githubusercontent.com/patrickshox/Mojave-Dark-RStudio-Theme/master/Mojave%20Dark.rstheme". Please check file system permissions.

Even after giving chmod 7777 to .R folder.

I ended up manually adding the theme.

**Comment by mscbuck** [comment]
For the record I also received this error!

**Comment by patrickshox** [comment]
Hmm. I wasn't able to reproduce that error, but maybe it's because you don't have permission to set `globally = TRUE`. I've edited the readme file's installation code so that `globally` is at its default FALSE value. Hopefully that fixes things. Please let me know if it doesn't.

**Comment by patrickshox** [comment]
After I settle on a finalish version, I'll make the .rstheme available for direct download (via drive), and add instructions for a manual installation option. Hopefully, that will resolve any installation issues.
