### ISSUE TITLE
Markdown headers font size and cursor placement issues

### ISSUE THREAD

**Issue by mxblsdl** [patrickshox/Mojave-Dark-RStudio-Theme#10]
It appears that the Rmarkdown `#headers` show up as slightly larger text than the other characters. This leads to the cursor location getting offset slightly after each character. This is most notable on longer text strings. For example:
![markdown_text](https://user-images.githubusercontent.com/37624866/72483157-eb53cc80-37b4-11ea-840e-d221b32938c7.png)

shows a header that I typed. It appears that my cursor is between the 'a' and 'r'. But when I type an '8' I get this:
![markdown_text2](https://user-images.githubusercontent.com/37624866/72483201-0b838b80-37b5-11ea-8324-40c422ef0811.png)

My cursor is a full character to the right between the 'r' and 't'

**Comment by patrickshox** [comment]
Interesting. I'm not experiencing the same issue. Could it be that you added and applied a non monospaced font?
![ezgif-7-fa9a48b365ee](https://user-images.githubusercontent.com/47332449/72483475-1f3beb80-37cf-11ea-81ba-bfd8ebe1021f.gif)

**Comment by mxblsdl** [comment]
My editor font is "Lucida Console". I don't even know where I would change the markdown font. I should mention this is on Windows.

**Comment by mxblsdl** [comment]
If anyone else finds this to be an issue I solved the problem by going into the theme file:
Windows:
Documents/.R/rstudio/themes

and commenting out the font-weight that is applied to headers. It appears the font weight adjusted the characters position.
```
.ace_heading {
     color: rgb(103,183,249);
    /* font-weight: 900; */
}
```
