### ISSUE TITLE
Margin column is white

### ISSUE THREAD

**Issue by AshesITR** [patrickshox/Mojave-Dark-RStudio-Theme#11]
The margin column (activate at Global Settings > Code > Display > Show margin) is white. 
Reference is Solarized Dark - I'd prefer a dark gray line thats easier on the eye - especially as it will be visible virtually all the time whenever any document is open in the editor pane.

![grafik](https://user-images.githubusercontent.com/2363178/72516879-b1d19e80-3852-11ea-8de7-89dabf88c7d6.png)

![grafik](https://user-images.githubusercontent.com/2363178/72516912-c2821480-3852-11ea-86a1-9a29aed13c3f.png)

**Comment by patrickshox** [comment]
Thanks for letting me know. In the latest push, the margin's rgb(76,77,86). Just run the install code again to get that updated.
