### ISSUE TITLE
Code completion is dark blue

### ISSUE THREAD

**Issue by AshesITR** [patrickshox/Mojave-Dark-RStudio-Theme#13]
Ace code completion (Ctrl/Cmd+Space) also looks like it has some dark blue elements (especially the borders).

![grafik](https://user-images.githubusercontent.com/2363178/72621541-be80f000-3941-11ea-8445-25bb421501c7.png)

Let me know if you appreciate pull requests. Maybe I can help you add some "missed" CSS selectors.

**Comment by patrickshox** [comment]
Thanks for making me aware. I addressed this issue and your previous issue in the latest commit. And I'm all for pull reqs 👍🏻.
