### ISSUE TITLE
Question about editing UI components??

### ISSUE THREAD

**Issue by davidgibsonp** [patrickshox/Mojave-Dark-RStudio-Theme#14]
Hey there! Thanks for creating such an amazing theme.

I have questions on how you edited the UI components of Rstudio. It looks like you are manually editing the `.rstheme` files. Is this the only way or have you been able to convert a `.tmTheme` file using the `convertTheme()` function from the Rstudio API? If you are indeed doing it manually do you have a good key of what edits what?

Asking because I have been ported over the **ayu** theme to Rstudio but have only edited the syntax not the windows or anything like that. 

Thanks!

**Comment by patrickshox** [comment]
I'm excited to see what you come up with 🙂. To style the main RStudio window, I think it'd be easiest to just use a [.tmtheme editor](https://tmtheme-editor.herokuapp.com/#!/editor/theme/Monokai) and then convert it to an .rstheme. In any case, to apply dark themes to the rest of the IDE, you'll have to manually edit an .rstheme file. It's not completely annotated, but the rstheme file in this repo actually has lots of comments explaining which components the selectors affect. Feel free to copy-paste selectors from this theme as necessary and edit the colors. Beyond that, the only way to know what selector affects what element is to right click on it and inspect it.
