### ISSUE TITLE
Dark style not showing across all IDE, issues with RStudio preview 1.3.776

### ISSUE THREAD

**Issue by GuiAlDuS** [patrickshox/Mojave-Dark-RStudio-Theme#15]
Hi, 
After I updated RStudio preview to version 1.3.776, the Packages Update window and the left panel of the General Options window appear white. I already updated to the latest version of the Mojave-Dark-RStudio-Theme but same issue.

Thanks!

**Comment by patrickshox** [comment]
This has been fixed.
