### ISSUE TITLE
Left pane in Global Options window not visible?

### ISSUE THREAD

**Issue by PrivacyMatter** [patrickshox/Mojave-Dark-RStudio-Theme#17]
Hi,

Thanks for the great theme!
There is one main issue that I encounter once applying it, though: when you open the settings menu (that allows, among other things, to apply different themes), the text on the left pane that lists the configuration options is barely visible; please see attached snapshot.
Is there a way to address this? 

Snapshot:

<img width="583" alt="Untitled 6" src="https://user-images.githubusercontent.com/36560766/76009681-9a707280-5edf-11ea-804b-1cb7965b0b5a.png">

Thanks!

**Comment by RMHogervorst** [comment]
I have the same issue, I'm running the preview RStudio Version 1.3.911

**Comment by PrivacyMatter** [comment]
Hi, I actually fixed it, I think.
Looking at the source, I realized that you can specify and override the properties any class in RStudio source.  
This realization by itself was priceless for me, for different reasons: please see my post https://community.rstudio.com/t/capturing-configuration-applied-via-rstudio-devtool-in-themes-or-in-a-project-file/55433 
Thank you, Patrick (is that your name?) for sharing this source which made me realize that.  It helped me fixed the issue mentioned in the post above and saves me lots of time.  

As for fixing the bug in this profile: I make the following simple changes to the rstheme file to set the background to black:
```
*** Mojave Dark (Static).orig.rstheme	2020-04-20 13:27:50.000000000 -0400
--- Mojave Dark (Static).rstheme	2020-03-05 13:51:16.000000000 -0500
***************
*** 162,179 ****
--- 162,184 ----
  /*button labels in Git commit page*/
  .GD15MCFCMU {
    color: white;
  }


+ .GGBOEFPDGK {
+   background: black;
+ }
+
  .dialogMiddleCenterInner button.gwt-Button.GD15MCFCH1 {
    filter: invert(90%)
  }

  .rstudio-themes-flat .gwt-TabLayoutPanelTabs table.rstheme_tabLayoutCenter, .rstudio-themes-flat .rstheme_minimizedWindowObject table.rstheme_tabLayoutCenter {
    border-radius: 0px;
  }
```

How do you figure out the class name? 
Use the "inspect element" when right clicking the place in the window that is closest to what you want to change; that would open the DevTool window, and you can interactively point to class names, and it will show you on the RStudio window which elements of the window they corresponds to.  It sometimes takes a while to figure out exactly the subclass you want to change, as there are lots of subcomponent and you can configure the style of  almost anything, but you can play with that, change values, in DevTool, etc, and you immediately see the results.
Once you recognize what you want to change, add it to a one of the themes.

Hope that helps.

**Comment by aldomann** [comment]
Can confirm this also occurs on the stable 1.3 release (RStudio 1.3.959).

**Comment by mattkerlogue** [comment]
Was just coming to say the same. Also seems to affect interface buttons within options window.

This is Mojave Dark in the stable release:
![image](https://user-images.githubusercontent.com/35345053/83151563-a0e44400-a0f4-11ea-8288-eee0f84c83c2.png)

Doesn't happen with the in-built dark themes, but that's because they don't change the skin.
![Screenshot 2020-05-28 at 15 00 29](https://user-images.githubusercontent.com/35345053/83151685-c7a27a80-a0f4-11ea-9995-87943702c2b2.png)

**Comment by PrivacyMatter** [comment]
Jus pointing out my follow up post above, showing how to fix it by adding 3 lines to the scheme file. It's easy and the problem goes away.  See post/comment above https://github.com/patrickshox/Mojave-Dark-RStudio-Theme/issues/17#issuecomment-616749543

**Comment by CLRafaelR** [comment]
EDIT:

I solved the problem by adding the following code. `Inspect element` does the trick!

```
.GGBOEFPDK2 {
  background: black;
}
```

@PrivacyMatter 

Related to the issue, currently the background of the pane "New R Markdown" is white and this makes the pane severely unreadable.  What and in which line should I add `.GGBOEFPDGK {background: black;}`-like command on the rstheme file?

![image](https://user-images.githubusercontent.com/42314553/86201709-3a42c200-bb9b-11ea-9816-cfe4935a0a49.png)

**Comment by PrivacyMatter** [comment]
Yep, that's how I found what needed to be changed also; Inspect element and waling the class tree there.  Note that whatever you are changing there become visible on the fly so you can experiment with it, etc.
I don't think that the location at the rstheme file matters much as long as it is not succeeded by another statement that modifies another class that you inherit from.  The whole system is hierarchical, so make sure you keep the changes near the leafs

Cheers

**Comment by patrickshox** [comment]
This issue has been resolved.

**Comment by ctfysh** [comment]
> This issue has been resolved.

Thanks! This issue has been resolved, but the update panel is still have the same problem. @patrickshox 

![update](https://user-images.githubusercontent.com/3131805/88372357-4d2a6a00-cdc8-11ea-8c4b-441a233e1de9.png)

**Comment by patrickshox** [comment]
That's been fixed now. Thanks for bringing this to my attention.
