### ISSUE TITLE
Uninstalling this theme

### ISSUE THREAD

**Issue by domsle** [patrickshox/Mojave-Dark-RStudio-Theme#18]
How do I remove this theme? I don't like some aspects, like not themed Keyboard Shortcuts section - so I would like to remove it. 

I deleted the ~/.rstudio-desktop directory - with no change at all.

**Comment by patrickshox** [comment]
Within the appearances pane of the RStudio preferences, there's a remove button. Just press it while the Mojave Dark theme is highlighted.

**Comment by domsle** [comment]
Thanks, sorry for this (as I see now) stupid question. I just thought that I need to do something more than that.
