### ISSUE TITLE
Enhancement: make git "review changes" window dark

### ISSUE THREAD

**Issue by hughjonesd** [patrickshox/Mojave-Dark-RStudio-Theme#2]
When you hit "commit" in the git panel, you get a new window which is white. It would be nice if this was dark too.

**Comment by patrickshox** [comment]
Thanks for pointing that out. I just committed a version, which should style that. I don't use Git with RStudio so please lmk if something doesn't look right.

**Comment by hughjonesd** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/5818871/65032907-019f6800-d93c-11e9-9806-820d88f36b6a.png">

It looks OK but with a couple of awkward bits in the history interface (dark blue text, one pale chunk).

**Comment by LDalby** [comment]
Thanks for this awesome theme! It's really nice!

In the git interface - Is it possible to also have the close button, frame and horizontal scroll bar dark?

![image](https://user-images.githubusercontent.com/2366579/65072456-38ec3400-d991-11e9-8c75-efcb5da3d2e6.png)

**Comment by patrickshox** [comment]
I'll try. But it'll be a few days as I have homework due tomorrow.

**Comment by LDalby** [comment]
Of course, no hurry! 

Thanks again for the effort with this theme 👍

**Comment by patrickshox** [comment]
I've committed another version, which should be MUCH better. Please let me know over the next few days if y'all notice anything off. Otherwise, I'll close this issue thread.

**Comment by LDalby** [comment]
The "close" button is still white, but otherwise it looks great! 
![image](https://user-images.githubusercontent.com/2366579/65220743-b90eb880-dabb-11e9-8722-cc2fdf9f6974.png)

**Comment by LDalby** [comment]
Ahh, I was a bit too fast. The horizontal scroll bar is actually still white, but the "close" button is now fixed 👍 
I also noticed that the "Your branch is ahead..." info line (behind the Git Push window in the image) is on a white background. Perhaps that could be darkened too?

![image](https://user-images.githubusercontent.com/2366579/65232102-e3b73c00-dad0-11e9-9fec-e5b612c263dc.png)
