### ISSUE TITLE
Global options appear white

### ISSUE THREAD

**Issue by malcalakovalski** [patrickshox/Mojave-Dark-RStudio-Theme#21]
The global options panel is completely white after installing and selecting the Mojave dark theme. I'm using RStudio 1.4.1103 on Mac OS Big Sur.
![mojave-dark-options](https://user-images.githubusercontent.com/56268747/105913721-3e34a680-5ffb-11eb-996a-b606a036644b.png)

**Comment by dyerlab** [comment]
Still white on MacOS 12.4 on RStudio 2022.07.1

**Comment by BatmanAlen** [comment]
Same here. I'm now using MacOS 13.0.1 Ventura.

**Comment by boiledbroccoli** [comment]
still white on MACOS 14.5

**Comment by gernophil** [comment]
Yes, I fixed this in my pull request, but somehow the fix doesn't work anymore. Gonna take another look into it.

**Comment by gernophil** [comment]
I just checked. There was some change between 2023.12.1 and 2024.04.0 that reversed all the changes I made. Guess I need to update some id's

**Comment by gernophil** [comment]
Fixed this. Some things are still hard to read. Maybe I‘ll find a solution for that. If anyone has a better way then hard coding the IDs, I'm open to suggestions :).
