### ISSUE TITLE
The font and background color of function hint

### ISSUE THREAD

**Issue by jubyshu** [patrickshox/Mojave-Dark-RStudio-Theme#4]
When moving the mouse to the function name, I can't see the hint popped up because of the color of its font and background.

![Screen Shot 2019-09-17 at 7.25.29 PM.png](https://i.loli.net/2019/09/17/2Rg57kGENXSYjMJ.png)

**Comment by patrickshox** [comment]
Thanks so much for making me aware! 😃 I committed another version which addresses that issue.
