### ISSUE TITLE
rstudioapi::getThemeInfo()

### ISSUE THREAD

**Issue by pat-s** [patrickshox/Mojave-Dark-RStudio-Theme#6]
returns

```r
rstudioapi::getThemeInfo()
$editor
[1] "Textmate (default)"

$global
[1] "Classic"

$dark
[1] FALSE

$foreground
[1] "rgb(248, 248, 242)"

$background
[1] "rgb(41, 42, 48)"
```

which makes it hard to apply automatic theme switching, especially because `dark = FALSE`. 

Thanks for the theme!

**Comment by patrickshox** [comment]
Hmm. I'm not sure I understand the issue. It seems you're using the default editor, yet you're fg & bg colors are from Mojave Dark. Also, when I run getThemeInfo, I get something different.
<img width="189" alt="Screen Shot 2019-09-28 at 10 35 02 AM" src="https://user-images.githubusercontent.com/47332449/65818033-a3943f80-e1db-11e9-925d-2d854d230656.png">

**Comment by pat-s** [comment]
I'm on v1.3.449, haven't yet checked with stable.

**Comment by patrickshox** [comment]
Okay. I'll close the issue then and I can always reopen it if it becomes an issue in stable RStudio.
