### ISSUE TITLE
Dynamic darkening; scrollbar thumb

### ISSUE THREAD

**Issue by DRuiCHEN** [patrickshox/Mojave-Dark-RStudio-Theme#7]
It is a nice feature to dynamically darken the plots and markdown pane. But in some cases I'd prefer to keep them light instead of constantly switching color. How can I modify the .rstheme file to make this happen?

An additional minor issue is about the style of the scrollbar thumb. It is the same as Rstudio's native dark theme and doesn't look consistent with Mojave Dark. Is it possible to change its color?
<img width="585" alt="Screen Shot 2019-10-05 at 16 34 23" src="https://user-images.githubusercontent.com/35321665/66261419-7ffc6680-e792-11e9-8c4c-af63962e78b8.png">

**Comment by DRuiCHEN** [comment]
I've resolved the first problem: simply comment out the codes under `/*Markup viewer*/` and `/*Plots viewer*/`.

But I also notice another problem related to the second one. The scrollbar track of the help pane seems to be controlled by a different selector. Its color is different from those of the other panes.
<img width="580" alt="Screen Shot 2019-10-05 at 19 14 04" src="https://user-images.githubusercontent.com/35321665/66263504-7508fc80-e7b9-11e9-969e-4138d1b14f87.png">

**Comment by patrickshox** [comment]
Enough people have requested a version without dynamic darkening that I've added a static version as well. I'll try to address the scrollbar issue if I can.

**Comment by DRuiCHEN** [comment]
Adding the following code seems to fix the scrollbar! 
(found and adapted from https://github.com/anthonynorth/rscodeio)

```
/* scrollbars */
::-webkit-scrollbar {
  height: calc(17px * 10 / 14) !important;
}
::-webkit-scrollbar-thumb {
  border: none !important;
  border-radius: 0 !important;
  background-color: rgba(121, 121, 121, 0.18) !important;
}

::-webkit-scrollbar-thumb:hover {
  background-color: rgba(100, 100, 100, 0.4) !important;
}

::-webkit-scrollbar-thumb:active {
  background-color: rgba(191, 191, 191, 0.3) !important;
}

::-webkit-scrollbar,
::-webkit-scrollbar-corner,
::-webkit-scrollbar-track {
  background-color: rgba(0, 0, 0, .05) !important;
}

::-webkit-scrollbar-track:vertical {
  box-shadow: inset 1px 0 0 0 var(--separator);
}
```

**Comment by patrickshox** [comment]
Wow! Thanks so much. I've altered the Drive and the GitHub files, and credited you and Anthony North.

**Comment by DRuiCHEN** [comment]
> Adding the following code seems to fix the scrollbar!
> (found and adapted from https://github.com/anthonynorth/rscodeio)
> 
> ```
> /* scrollbars */
> ::-webkit-scrollbar {
>   height: calc(17px * 10 / 14) !important;
> }
> ::-webkit-scrollbar-thumb {
>   border: none !important;
>   border-radius: 0 !important;
>   background-color: rgba(121, 121, 121, 0.18) !important;
> }
> 
> ::-webkit-scrollbar-thumb:hover {
>   background-color: rgba(100, 100, 100, 0.4) !important;
> }
> 
> ::-webkit-scrollbar-thumb:active {
>   background-color: rgba(191, 191, 191, 0.3) !important;
> }
> 
> ::-webkit-scrollbar,
> ::-webkit-scrollbar-corner,
> ::-webkit-scrollbar-track {
>   background-color: rgba(0, 0, 0, .05) !important;
> }
> 
> ::-webkit-scrollbar-track:vertical {
>   box-shadow: inset 1px 0 0 0 var(--separator);
> }
> ```

Probably due to some updates in the MacOS Catalina, Rstudio would use the mac-style scrollbar if there is no customization. So now I would suggest abandoning these codes coz the default ones look cool already!

**Comment by patrickshox** [comment]
Okay cool, I've removed those lines.
